bazarr/1.5.4_beta18 package update

diff --git a/src/packages/bazarr/melange.yaml b/src/packages/bazarr/melange.yaml
--- a/src/packages/bazarr/melange.yaml
+++ b/src/packages/bazarr/melange.yaml
@@ -1,6 +1,6 @@
 package:
   name: bazarr
-  version: "1.5.4_beta17"
+  version: "1.5.4_beta18"
   epoch: 0
   description: Bazarr is a companion application to Sonarr and Radarr. It manages and downloads subtitles based on your requirements. You define your preferences by TV show or movie and Bazarr takes care of everything for you.
   copyright:
@@ -9,13 +9,11 @@ package:
     runtime:
       - unrar
       - ffmpeg
-
 var-transforms:
   - from: "${{package.version}}"
     match: "_beta"
     replace: "-beta."
     to: mangled-package-version
-
 environment:
   environment:
     PYTHONHASHSEED: 0
@@ -27,25 +25,21 @@ environment:
       - py3.13-virtualenv-bin
       - nodejs
       - npm
-
 pipeline:
   - uses: git-checkout
     with:
       expected-commit: f0ae7d6e913add636d36af30b7c74b511427b63e
       repository: https://github.com/morpheus65535/bazarr
       tag: v${{vars.mangled-package-version}}
-  
   - uses: patch
     with:
       patches: GHSA-h95x-26f3-88hr.patch
-  
   - name: Build frontend
     working-directory: /home/build/frontend
     runs: |
       npx update-browserslist-db@latest
       npm install
       npm run build
-  
   - name: Update vendored dependencies
     runs: |
       set -euo pipefail
@@ -78,44 +72,10 @@ pipeline:
               echo "Warning: $LIBS_DIR/$OLD_DIST not found, skipping"
           fi
       done
-  
   - name: Fix SSL verification
-    runs: |
-      set -euo pipefail
-      
-      if ! head -n 15 "libs/urllib3/connectionpool.py" | grep -q "import ssl"; then
-        sed -i '/from __future__ import annotations/a import ssl' "libs/urllib3/connectionpool.py"
-        echo "'ssl package import' has been added to the top of the file."
-      else
-        echo "'ssl package is already imported."
-      fi
-      
-      sed -i 's/cert_reqs=self\.cert_reqs/cert_reqs=ssl.CERT_REQUIRED/' "libs/urllib3/connectionpool.py"  
-  
+    runs: "set -euo pipefail\n\nif ! head -n 15 \"libs/urllib3/connectionpool.py\" | grep -q \"import ssl\"; then\n  sed -i '/from __future__ import annotations/a import ssl' \"libs/urllib3/connectionpool.py\"\n  echo \"'ssl package import' has been added to the top of the file.\"\nelse\n  echo \"'ssl package is already imported.\"\nfi\n\nsed -i 's/cert_reqs=self\\.cert_reqs/cert_reqs=ssl.CERT_REQUIRED/' \"libs/urllib3/connectionpool.py\"  \n"
   - name: Prepare package
-    runs: |
-      set -euo pipefail
-
-      APPDIR="${{targets.destdir}}/usr/lib/bazarr/app"
-      FILE_LIST="$(cat .github/files_to_copy)"
-      
-      mkdir -p "${APPDIR}" 
-      virtualenv --copies "${APPDIR}/venv"
-      sed -i '/lxml/ s/lxml>=4.3.0, <5.0.0/lxml>=5.0.0/' requirements.txt
-      sh -c "source '${APPDIR}/venv/bin/activate' && pip install --upgrade --no-cache-dir -r requirements.txt -r postgres-requirements.txt"    
-      
-      git describe --abbrev=0 > VERSION
-
-      while IFS= read -r f
-      do
-          echo "**** copying $f to release ****"
-          cp -r --parents "$f" "$APPDIR"
-      done < .github/files_to_copy      
-      
-      cp VERSION "${APPDIR}"
-      
-      printf "UpdateMethod=docker\nBranch=master\nPackageVersion=${{package.version}}\nPackageAuthor=[d4rkfella](https://github.com/d4rkfella)" > ${{targets.destdir}}/usr/lib/bazarr/package_info
-
+    runs: "set -euo pipefail\n\nAPPDIR=\"${{targets.destdir}}/usr/lib/bazarr/app\"\nFILE_LIST=\"$(cat .github/files_to_copy)\"\n\nmkdir -p \"${APPDIR}\" \nvirtualenv --copies \"${APPDIR}/venv\"\nsed -i '/lxml/ s/lxml>=4.3.0, <5.0.0/lxml>=5.0.0/' requirements.txt\nsh -c \"source '${APPDIR}/venv/bin/activate' && pip install --upgrade --no-cache-dir -r requirements.txt -r postgres-requirements.txt\"    \n\ngit describe --abbrev=0 > VERSION\n\nwhile IFS= read -r f\ndo\n    echo \"**** copying $f to release ****\"\n    cp -r --parents \"$f\" \"$APPDIR\"\ndone < .github/files_to_copy      \n\ncp VERSION \"${APPDIR}\"\n\nprintf \"UpdateMethod=docker\\nBranch=master\\nPackageVersion=${{package.version}}\\nPackageAuthor=[d4rkfella](https://github.com/d4rkfella)\" > ${{targets.destdir}}/usr/lib/bazarr/package_info\n"
 test:
   environment:
     contents:
@@ -129,11 +89,9 @@ test:
       uses: test/tw/ldd-check
       with:
         packages: ${{package.name}}
-    
     - name: Run test script
       runs: |
         EXPECTED_VERSION="${{ vars.package.version }}" test/test.sh
-
 update:
   enabled: true
   version-transform:
